import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { WebSocket } from 'ws';

import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { CompiledContract } from '@midnight-ntwrk/midnight-js-protocol/compact-js';
import { createUnprovenCallTx } from '@midnight-ntwrk/midnight-js-contracts';
import { setNetworkId } from '@midnight-ntwrk/midnight-js-network-id';

// @ts-expect-error WebSocket
globalThis.WebSocket = WebSocket;

setNetworkId('preview');

async function test() {
  console.log('Testing direct proof generation via Proof Server...');
  const zkConfigPath = path.resolve('contracts/midnight/managed');
  const contractPath = path.join(zkConfigPath, 'contract', 'index.js');
  const Nivaan = await import(contractPath);

  const { createNivaanWitnesses } = await import('../contracts/midnight/witnesses.ts');
  const witnesses = createNivaanWitnesses();

  const compiledContract = CompiledContract.make('nivaan', Nivaan.Contract).pipe(
    CompiledContract.withWitnesses(witnesses),
    CompiledContract.withCompiledFileAssets(zkConfigPath),
  );

  const zkConfigProvider = new NodeZkConfigProvider(zkConfigPath);
  const proofServerUrl = 'http://localhost:6300';
  const proofProvider = httpClientProofProvider(proofServerUrl, zkConfigProvider);

  const indexer = 'https://indexer.preview.midnight.network/api/v4/graphql';
  const indexerWS = 'wss://indexer.preview.midnight.network/api/v4/graphql/ws';
  const publicDataProvider = indexerPublicDataProvider(indexer, indexerWS);

  // Dummy or real coin public key (64 hex chars)
  const dummyCoinPublicKey = '00'.repeat(32);
  const dummyEncPublicKey = '00'.repeat(32);
  const walletProvider = {
    getCoinPublicKey: () => dummyCoinPublicKey,
    getEncryptionPublicKey: () => dummyEncPublicKey,
  };

  const stateMap = new Map();
  const privateStateId = 'testPrivateState';
  stateMap.set(privateStateId, {
    aadhaarQrData: '413980064395675672371227137711583253818588855011140279517448839820612623632349901856184351959999993482778047983380439368130654000523344778832306969762570511482',
  });
  const privateStateProvider = {
    get: async (id) => stateMap.get(id) ?? null,
    set: async (id, val) => { stateMap.set(id, val); },
    clear: async () => { stateMap.clear(); },
    setContractAddress: () => {},
  };

  const contractAddress = '18d036ffb45f2d594b8747e4ab0da92ada4fe58a6b6765bc58364369e6680eaa';

  const providers = {
    zkConfigProvider,
    proofProvider,
    publicDataProvider,
    walletProvider,
    privateStateProvider,
  };

  console.log('1. Creating unproven call tx for checkNotRevoked...');
  const did = new Uint8Array(32);
  const unprovenCallTx = await createUnprovenCallTx(providers, {
    compiledContract: compiledContract,
    contractAddress,
    circuitId: 'checkNotRevoked',
    args: [did],
    privateStateId,
  });

  console.log('Unproven call tx created successfully!');
  console.log('Circuit result:', unprovenCallTx.private.result);

  console.log('2. Submitting to Proof Server via proofProvider.proveTx...');
  const startTime = Date.now();
  const provenTx = await proofProvider.proveTx(unprovenCallTx.private.unprovenTx);
  const elapsed = (Date.now() - startTime) / 1000;
  console.log(`Proof generated by Proof Server in ${elapsed}s!`);
  console.log('ProvenTx:', provenTx);
}

test().catch(console.error);
